import { mWorld } from "./mWorld";

export const queries = {
    // planckBody: mWorld.with("planck"),
    spriteConfigs: mWorld.with("position", "spriteKey"),
    sprites: mWorld.with("spriteObject"),
    pPolygonConfigs: mWorld.with("points", "isClosedPath").without("position"),
    pPolygons: mWorld.with("polygonObject"),
    ballBodyConfigs: mWorld.with("ballConfig", "ball", "position", "size"),
    ballBodies: mWorld.with("ballBody"),
    wallBodyConfigs: mWorld.with("wall", "points", "bouncy", "isClosedPath").without("position"),
    wallBodies: mWorld.with("wallBody"),
    rectConfigs: mWorld.with("rectConfig", "position"),
    rectBodyConfigs: mWorld.with("rectBodyTag", "rectConfig", "position"),
    rects: mWorld.with("rectObject"),
    rectBodies: mWorld.with("rectBody"),
    balls: mWorld.with("ball", "spriteObject", "ballBody"),
    walls: mWorld.with("wall", "wallBody", "polygonObject"),
    void: mWorld.with("voidZone", "wall"),
    // flippers: mWorld.with("flipperConfig", "planck", "position"),
    // flipperShape: mWorld.with("flipperConfig", "planck", "position", "renderShape"),
    isFlippable: mWorld.with("motorSpeed", "flipperJoint"),
    leftFlip: mWorld.with("flipperConfig").where(({flipperConfig}) => flipperConfig.side === "left"),
    rightFlip: mWorld.with("flipperConfig").where(({flipperConfig}) => flipperConfig.side === "right"),
    contactData: mWorld.with("contactPoint", "contactEntityA", "contactEntityB", "contactType"),
    particles: mWorld.with("ballRank", "emitters"),
    explosionBox: mWorld.with("explosionBox", "contactPoint"),
    controllableByKeyDown: mWorld.with("keyBoardKey", "onKeyDown"),
    controllableByKeyJustDown: mWorld.with("keyBoardKey", "onKeyJustDown"),
    controllableByKeyUp: mWorld.with("keyBoardKey", "onKeyUp"),
    audio: mWorld.with("audioKey"),
    shrinkables: mWorld.with("shrink", "ball", "size", "sprite", "ballRank"),
    marker: mWorld.with("position", "sprite", "marker"),
    movableSprites: mWorld.with("movable", "sprite", "position", "angle")
}